ALTER TABLE career_saves ADD COLUMN training_focus VARCHAR(30) NOT NULL DEFAULT 'BALANCED';
ALTER TABLE players ADD COLUMN age INTEGER NOT NULL DEFAULT 24;

UPDATE clubs SET balance = 5000000 WHERE balance = 0;
