CREATE TABLE publishers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name VARCHAR(160) NOT NULL UNIQUE,
    canonical_domain VARCHAR(255),
    official BOOLEAN NOT NULL DEFAULT FALSE,
    trust_score NUMERIC(5, 4) NOT NULL DEFAULT 0.5000,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_publishers_trust_score CHECK (trust_score >= 0 AND trust_score <= 1)
);

ALTER TABLE news_sources
    ADD COLUMN publisher_id BIGINT REFERENCES publishers(id),
    ADD COLUMN provider VARCHAR(32) NOT NULL DEFAULT 'rss',
    ADD COLUMN config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN config_version INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN credential_ref VARCHAR(120),
    ADD COLUMN fetch_interval_seconds INTEGER NOT NULL DEFAULT 900;

INSERT INTO publishers (
    created_at,
    updated_at,
    name,
    canonical_domain,
    official,
    trust_score,
    active
)
SELECT
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    source.name,
    NULL,
    FALSE,
    0.5000,
    source.active
FROM news_sources source
ON CONFLICT (name) DO NOTHING;

UPDATE news_sources source
SET publisher_id = publisher.id
FROM publishers publisher
WHERE publisher.name = source.name
  AND source.publisher_id IS NULL;

ALTER TABLE news_sources
    ALTER COLUMN feed_url TYPE TEXT;

ALTER TABLE news_articles
    ALTER COLUMN source_url TYPE TEXT,
    ADD COLUMN content_kind VARCHAR(24) NOT NULL DEFAULT 'EDITORIAL',
    ADD COLUMN verification_status VARCHAR(24),
    ADD COLUMN confidence_score NUMERIC(5, 4),
    ADD COLUMN image_url TEXT,
    ADD COLUMN media_type VARCHAR(20),
    ADD COLUMN first_source_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN last_source_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN last_material_change_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN source_count_cached INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN summary_basis_hash VARCHAR(64),
    ADD COLUMN merged_into_id BIGINT REFERENCES news_articles(id),
    ADD CONSTRAINT chk_news_articles_confidence
        CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)),
    ADD CONSTRAINT chk_news_articles_source_count
        CHECK (source_count_cached >= 0);

CREATE TABLE raw_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    publisher_id BIGINT REFERENCES publishers(id),
    connector_id BIGINT NOT NULL REFERENCES news_sources(id),
    provider VARCHAR(32) NOT NULL,
    external_id TEXT,
    identity_key TEXT NOT NULL UNIQUE,
    revision_fingerprint VARCHAR(64) NOT NULL,
    original_url TEXT NOT NULL,
    canonical_url TEXT,
    canonical_url_hash VARCHAR(64),
    content_type VARCHAR(20) NOT NULL,
    title VARCHAR(500),
    description TEXT,
    author_name VARCHAR(200),
    author_username VARCHAR(120),
    image_url TEXT,
    embed_url TEXT,
    language VARCHAR(20),
    published_at TIMESTAMP(6) WITH TIME ZONE,
    modified_at TIMESTAMP(6) WITH TIME ZONE,
    discovered_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    payload_version INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE UNIQUE INDEX uq_raw_items_provider_external
    ON raw_items(connector_id, provider, external_id)
    WHERE external_id IS NOT NULL;
CREATE INDEX idx_raw_items_canonical_hash ON raw_items(canonical_url_hash);
CREATE INDEX idx_raw_items_publisher_published ON raw_items(publisher_id, published_at DESC);
CREATE INDEX idx_raw_items_connector_published ON raw_items(connector_id, published_at DESC);

CREATE TABLE story_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL REFERENCES news_articles(id),
    raw_item_id BIGINT NOT NULL REFERENCES raw_items(id),
    role VARCHAR(20) NOT NULL DEFAULT 'PRIMARY',
    relevance_score NUMERIC(5, 4),
    added_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_story_items_membership UNIQUE (story_id, raw_item_id),
    CONSTRAINT chk_story_items_relevance
        CHECK (relevance_score IS NULL OR (relevance_score >= 0 AND relevance_score <= 1))
);

CREATE UNIQUE INDEX uq_story_items_primary
    ON story_items(story_id)
    WHERE role = 'PRIMARY';
CREATE INDEX idx_story_items_raw_item ON story_items(raw_item_id);
CREATE INDEX idx_story_items_story_added ON story_items(story_id, added_at);

ALTER TABLE news_articles
    ADD COLUMN hero_raw_item_id BIGINT REFERENCES raw_items(id);

CREATE TABLE story_key_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL REFERENCES news_articles(id),
    ordinal INTEGER NOT NULL,
    text VARCHAR(1000) NOT NULL,
    confidence NUMERIC(5, 4),
    CONSTRAINT uq_story_key_points_ordinal UNIQUE (story_id, ordinal),
    CONSTRAINT chk_story_key_points_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE TABLE key_point_sources (
    key_point_id BIGINT NOT NULL REFERENCES story_key_points(id) ON DELETE CASCADE,
    raw_item_id BIGINT NOT NULL REFERENCES raw_items(id),
    evidence_field VARCHAR(40) NOT NULL,
    relation VARCHAR(20) NOT NULL,
    PRIMARY KEY (key_point_id, raw_item_id, evidence_field)
);

CREATE INDEX idx_key_point_sources_raw_item ON key_point_sources(raw_item_id);
CREATE INDEX idx_news_article_tags_tag_article ON news_article_tags(tag_id, article_id);
CREATE INDEX idx_news_articles_story_feed
    ON news_articles(last_material_change_at DESC, id DESC)
    WHERE status = 'PUBLISHED';

DROP INDEX IF EXISTS idx_news_articles_fts;
CREATE INDEX idx_news_articles_fts
    ON news_articles
    USING GIN(to_tsvector('simple',
        title || ' ' || COALESCE(summary, '') || ' ' || COALESCE(content, '')
    ));
