alter table users add column if not exists email_verified boolean not null default false;
alter table users add column if not exists email_verified_at timestamp(6) with time zone;

-- Existing accounts predate the verification requirement and remain usable after this migration.
update users
set email_verified = true,
    email_verified_at = coalesce(email_verified_at, current_timestamp)
where email_verified = false;

create table auth_action_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    purpose varchar(32) not null,
    token_hash char(64) not null unique,
    expires_at timestamp(6) with time zone not null,
    consumed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null default current_timestamp
);

create unique index uq_auth_action_tokens_active_purpose
    on auth_action_tokens(user_id, purpose)
    where consumed_at is null;

create index idx_auth_action_tokens_expiry on auth_action_tokens(expires_at);

create table auth_rate_limit_windows (
    id bigint generated by default as identity primary key,
    action varchar(32) not null,
    identity_hash char(64) not null,
    window_started_at timestamp(6) with time zone not null,
    attempts integer not null,
    unique (action, identity_hash)
);

create table auth_mail_outbox (
    id bigint generated by default as identity primary key,
    recipient_user_id bigint not null references users(id) on delete cascade,
    purpose varchar(32) not null,
    encrypted_payload text not null,
    attempts integer not null default 0,
    next_attempt_at timestamp(6) with time zone not null default current_timestamp,
    sent_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    last_error varchar(120),
    created_at timestamp(6) with time zone not null default current_timestamp
);

create index idx_auth_mail_outbox_pending
    on auth_mail_outbox(next_attempt_at)
    where sent_at is null;
