create table telegram_delivery_outbox (
    id bigint generated by default as identity primary key,
    article_id bigint not null unique references news_articles(id),
    attempts integer not null default 0,
    next_attempt_at timestamp(6) with time zone not null default current_timestamp,
    sent_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    last_error varchar(120),
    created_at timestamp(6) with time zone not null default current_timestamp
);

create index idx_telegram_delivery_outbox_pending
    on telegram_delivery_outbox(next_attempt_at)
    where sent_at is null and failed_at is null;
