CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE raw_items
    ADD COLUMN IF NOT EXISTS embedding vector(384),
    ADD COLUMN IF NOT EXISTS embedding_model VARCHAR(160),
    ADD COLUMN IF NOT EXISTS embedding_revision VARCHAR(120),
    ADD COLUMN IF NOT EXISTS embedded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cluster_status VARCHAR(32) NOT NULL DEFAULT 'PENDING';

CREATE TABLE IF NOT EXISTS story_cluster_profiles (
    story_id BIGINT PRIMARY KEY REFERENCES news_articles(id) ON DELETE CASCADE,
    centroid vector(384) NOT NULL,
    model VARCHAR(160) NOT NULL,
    model_revision VARCHAR(120) NOT NULL,
    member_count INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_story_cluster_member_count CHECK (member_count > 0)
);

ALTER TABLE story_items
    ADD COLUMN IF NOT EXISTS semantic_score NUMERIC(6,5),
    ADD COLUMN IF NOT EXISTS lexical_score NUMERIC(6,5),
    ADD COLUMN IF NOT EXISTS final_cluster_score NUMERIC(6,5),
    ADD COLUMN IF NOT EXISTS cluster_method VARCHAR(40);

CREATE TABLE IF NOT EXISTS cluster_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_item_id BIGINT NOT NULL REFERENCES raw_items(id),
    selected_story_id BIGINT REFERENCES news_articles(id),
    action VARCHAR(32) NOT NULL,
    model VARCHAR(160),
    model_revision VARCHAR(120),
    semantic_score NUMERIC(6,5),
    lexical_score NUMERIC(6,5),
    entity_score NUMERIC(6,5),
    time_score NUMERIC(6,5),
    final_score NUMERIC(6,5),
    reason_code VARCHAR(80) NOT NULL,
    candidate_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_news_articles_cluster_window
    ON news_articles(last_source_at DESC)
    WHERE status = 'PUBLISHED'
      AND content_kind = 'AGGREGATED_STORY';

CREATE INDEX IF NOT EXISTS idx_cluster_decisions_raw_item ON cluster_decisions(raw_item_id);
CREATE INDEX IF NOT EXISTS idx_cluster_decisions_story ON cluster_decisions(selected_story_id);
