create table minigame_players (
    id bigint generated by default as identity primary key,
    provider_player_id bigint not null unique,
    name varchar(160) not null,
    normalized_name varchar(180) not null,
    aliases text not null default '[]',
    nationality varchar(100),
    position varchar(80),
    birth_year integer,
    current_club varchar(160),
    current_league varchar(160),
    career_clubs text not null default '[]',
    season_label varchar(100),
    season_appearances integer,
    season_goals integer,
    season_assists integer,
    trophy_count integer not null default 0,
    refreshed_at timestamp(6) with time zone not null
);

create index idx_minigame_players_normalized_name on minigame_players(normalized_name);

create table minigame_challenges (
    id bigint generated by default as identity primary key,
    play_date date not null,
    game_type varchar(20) not null,
    public_payload text not null,
    answer_payload text not null,
    created_at timestamp(6) with time zone not null,
    unique (play_date, game_type)
);

create table minigame_attempts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    challenge_id bigint not null references minigame_challenges(id),
    attempt_key varchar(80) not null,
    mode varchar(20) not null,
    status varchar(20) not null,
    version bigint not null default 0,
    wrong_guesses integer not null default 0,
    revealed_clues integer not null default 0,
    score integer not null default 0,
    state_payload text not null default '{}',
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    unique (user_id, challenge_id, attempt_key)
);

create index idx_minigame_attempts_challenge_rank on minigame_attempts(challenge_id, mode, score desc, completed_at asc);
