CREATE TABLE news_ai_enrichment_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL REFERENCES news_articles(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    fallback_summary TEXT,
    summary_basis_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    failed_at TIMESTAMP(6) WITH TIME ZONE,
    last_error VARCHAR(120),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (story_id, summary_basis_hash)
);

CREATE INDEX idx_news_ai_enrichment_pending
    ON news_ai_enrichment_outbox(status, next_attempt_at)
    WHERE status IN ('PENDING', 'PROCESSING');
