create table moderation_audit_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    actor_id bigint,
    action varchar(80) not null,
    target_type varchar(40) not null,
    target_id bigint,
    reason varchar(300)
);

create index idx_moderation_audit_created on moderation_audit_logs(created_at desc);
