package com.footballverse.game.dto;

public enum EventType {
    KICKOFF, PASS, CARRY, TACKLE, TURNOVER, FOUL, YELLOW_CARD, RED_CARD, SHOT, SAVE, GOAL, INJURY, SUBSTITUTION, HALF_TIME, FULL_TIME, MANAGER_DECISION
}
