package com.footballverse.game.dto;

public enum PlayerRole {
    GOALKEEPER,
    SWEEPER_KEEPER,
    FULL_BACK,
    WING_BACK,
    CENTRAL_DEFENDER,
    STOPPER,
    COVER,
    BALL_PLAYING_DEFENDER,
    ANCHOR,
    BALL_WINNER,
    DEEP_LYING_PLAYMAKER,
    CENTRAL_MIDFIELDER,
    BOX_TO_BOX,
    ADVANCED_PLAYMAKER,
    ATTACKING_MIDFIELDER,
    WINGER,
    INSIDE_FORWARD,
    POACHER,
    TARGET_FORWARD,
    PRESSING_FORWARD,
    COMPLETE_FORWARD
}
